### PR TITLE
Creates a non-root user in docker image and passes user context when building image

### PR DESCRIPTION
**Pull request by lorengordon**
Prior to this patch, files created in the docker volume mounts were
owned by root, which causes permissions issues when accessing those
files outside the container.

This was particularly evident when running the mockstack/pytest target
(which operates inside the container), followed by running the terraform/pytest
target (which operates outside the container).

With this patch, files created in the mounted filesystem will be owned by
the user running the docker container, so there should no longer be
any permissions issues.

### CODE REVIEW

**Comment by kbalk** [comment]
There's still a problem here.  I made sure there is no docker image for the file-cache repo and no existing `.filecache` directory, but `make mockstack/pytest` is still creating files as root:

```
make mockstack/clean
docker ps -a
docker images -a
sudo rm -rf tests/filecache/.filecache
make mockstack/up
make mockstack/pytest
ls -la tests/filecache/.filecache
```

The `make -C /${PROJECT_NAME} install` is run as USER, but is the actual target run as user?

**Comment by lorengordon** [comment]
Oops, I forgot an important part of the test setup! Because each calling project pins the version of the tardigrade-ci container, we need to rebuild it with this branch checked out, and force the project to use the built image. Here's how I did it:

1. Check docker and delete both the `tardigrade-ci:latest` image and the "integration-test" image for the calling project
2. In the tardigrade-ci directory, with this branch checked out, run: `IMAGE_ID= make docker/build`. This will build the image with the name `tardigrade-ci:latest`
3. In the calling project directory, modify the Dockerfile to specify: `FROM tardigrade-ci:latest`, so the name matches the image just built
4. Ensure the directory in question does not already exist: `sudo rm -rf tests/filecache/.filecache`
5. Now run `mockstack/pytest`

```
❯ ls -al tests/filecache/.filecache/
total 20
drwxr-xr-x 5 loren loren 4096 Jul 28 13:01 .
drwxr-xr-x 4 loren loren 4096 Jul 28 13:01 ..
drwxr-xr-x 2 loren loren 4096 Jul 28 13:01 044364054148bfb6267508d4e0498ee64dd460c3fe167c30332cb0a5eb25524b
drwxr-xr-x 2 loren loren 4096 Jul 28 13:01 78863e8ea7ee5355d462a5df4afe22d14459f329e0db126b374dce1026a25ab7
drwxr-xr-x 2 loren loren 4096 Jul 28 13:01 b8b660a1d62cb1d58a5eb4becc6d4351d0f661e5dfbc8d01ca4cf5bceb27d0a7
```

**Comment by kbalk** [comment]
Still not working.  I did create the image per your instructions:

```
$ docker ps -a
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES

$ docker images -a
REPOSITORY              TAG       IMAGE ID       CREATED         SIZE
tardigrade-ci           latest    3fe4e53a2aba   6 minutes ago   1.68GB
localstack/localstack   latest    67efaf783f87   7 days ago      759MB

$ more Dockerfile
FROM plus3it/tardigrade-ci:latest

COPY requirements.txt /app/requirements.txt

RUN python -m pip install -r /app/requirements.txt
```

You might want to remove the "WIP" from this PR title and update the changelog.

**Comment by kbalk** [comment]
Just in case you're wondering:

```
$ IMAGE_ID= make docker/build
[docker/build]: building docker image named: tardigrade-ci:latest
[ -n "" ] && echo "[docker/build]: Image already present: " || \
DOCKER_BUILDKIT=1 docker build -t tardigrade-ci:latest \
	--build-arg USER_ID=$(id -u) \
	--build-arg GROUP_ID=$(id -g) \
	-f Dockerfile .
[+] Building 143.1s (15/15) FINISHED                                            
 => [internal] load build definition from Dockerfile                       0.1s
 => => transferring dockerfile: 990B                                       0.0s
 => [internal] load .dockerignore                                          0.0s
 => => transferring context: 2B                                            0.0s
 => [internal] load metadata for docker.io/library/python:3.9.6-buster     0.8s
 => [internal] load metadata for docker.io/library/golang:1.16.6-buster    0.9s
 => [stage-1 1/8] FROM docker.io/library/python:3.9.6-buster@sha256:59f4c  4.9s
 => => resolve docker.io/library/python:3.9.6-buster@sha256:59f4ce1606587  0.0s
 => => sha256:780d55ef3a6171674be69ea95254e96b1996bed7088 2.22kB / 2.22kB  0.0s
 => => sha256:cba42c28d9b81a80b75165cc9b61a71828c30be2b68 8.35kB / 8.35kB  0.0s
 => => sha256:59f4ce1606587995e38fe148b9218375418d0ef273f 1.86kB / 1.86kB  0.0s
 => => sha256:87cbe84263a0aba6329b72181788f940d1212f64f34 2.35MB / 2.35MB  2.1s
 => => extracting sha256:87cbe84263a0aba6329b72181788f940d1212f64f34dc2ca  2.5s
 => [internal] load build context                                          0.7s
 => => transferring context: 1.72MB                                        0.6s
 => [golang 1/1] FROM docker.io/library/golang:1.16.6-buster@sha256:f392  31.9s
 => => resolve docker.io/library/golang:1.16.6-buster@sha256:f3923dc5a92a  0.0s
 => => sha256:f3923dc5a92a237db0f07a924a238a8a4a711e3b77a 1.86kB / 1.86kB  0.0s
 => => sha256:028d102f774acfd5d9a17d60dc321add40bea5cc6f0 6.99kB / 6.99kB  0.0s
 => => sha256:60d87036a5ef3cd02b3a7acf1dce82071716a84e03e 1.79kB / 1.79kB  0.0s
 => => sha256:6182a456504bb119011b721ede5d1e6cf4d06214 68.75MB / 68.75MB  11.5s
 => => sha256:cc29a487638239fd8dbd95edec35e479575d7d 129.05MB / 129.05MB  17.9s
 => => sha256:ff36ba4656980ea99a067c8a9b39f210a4da82badccaa2b 155B / 155B  0.6s
 => => extracting sha256:6182a456504bb119011b721ede5d1e6cf4d0621447465d80  8.9s
 => => extracting sha256:cc29a487638239fd8dbd95edec35e479575d7da115cd3e7  10.5s 
 => => extracting sha256:ff36ba4656980ea99a067c8a9b39f210a4da82badccaa2ba  0.0s 
 => [stage-1 2/8] RUN addgroup --gid 1000 tardigrade-ci     && adduser --  3.9s 
 => [stage-1 3/8] COPY --from=golang /usr/local/go/ /usr/local/go/         3.7s 
 => [stage-1 4/8] RUN apt-get update -y && apt-get install -y     xz-util  7.1s 
 => [stage-1 5/8] COPY --chown=tardigrade-ci:tardigrade-ci --from=golang   0.1s 
 => [stage-1 6/8] COPY --chown=tardigrade-ci:tardigrade-ci . /tardigrade-  0.8s 
 => [stage-1 7/8] RUN make -C /tardigrade-ci install                      77.8s 
 => [stage-1 8/8] WORKDIR /tardigrade-ci                                   0.1s 
 => exporting to image                                                    14.0s 
 => => exporting layers                                                   14.0s 
 => => writing image sha256:3fe4e53a2aba3fb24a6e458c26b749a20396a687018b6  0.0s 
 => => naming to docker.io/library/tardigrade-ci:latest                    0.0s 
[docker/build]: Docker image build complete              
```

**Comment by lorengordon** [comment]
The name of the container needs to be _exactly_ the name of the built image... Instead of this:

```
$ more Dockerfile
FROM plus3it/tardigrade-ci:latest
```

Edit it so it read like this:

```
$ more Dockerfile
FROM tardigrade-ci:latest
```

Then build the "integration-test" image again...

**Comment by kbalk** [comment]
I don't know what's going on now:

```
>             os.symlink(link_src, link_dst)
E             PermissionError: [Errno 13] Permission denied: '/tardigrade-ci/tests/terraform_pytest/mockstack.tf' -> '/workdir/tests/filecache/prereq/mockstack.tf'
```

**Comment by lorengordon** [comment]
That's a strange one... I guess all I can think of is to run the container in interactive mode with a shell entrypoint and start exploring...

```
❯ docker run --network terraform_pytest_default --rm -e MOCKSTACK_HOST=localstack -e PYTEST_ARGS="" -v "/home/loren/git/repos/terraform-external-file-cache/:/workdir/" -v "/home/loren/git/repos/tardigrade-ci/:/tardigrade-ci/" -v "/home/loren/.aws/:/root/.aws/" -e AWS_DEFAULT_REGION=us-east-1 -w /workdir/ --entrypoint bash -it terraform-external-file-cache-integration-test:latest

tardigrade-ci@ddee8c78a775:/workdir$ whoami
tardigrade-ci

tardigrade-ci@ddee8c78a775:/workdir$ pwd
/workdir

tardigrade-ci@ddee8c78a775:/workdir$ ls -al
total 104
drwxr-xr-x 7 tardigrade-ci tardigrade-ci  4096 Jul 28 20:09 .
drwxr-xr-x 1 root          root           4096 Jul 29 02:01 ..
-rw-r--r-- 1 tardigrade-ci tardigrade-ci   130 Jul 28 19:56 .bumpversion.cfg
-rw-r--r-- 1 tardigrade-ci tardigrade-ci   333 Jul 28 19:56 .editorconfig
drwxr-xr-x 8 tardigrade-ci tardigrade-ci  4096 Jul 28 20:09 .git
-rw-r--r-- 1 tardigrade-ci tardigrade-ci    68 Jul 25 14:40 .gitattributes
drwxr-xr-x 2 tardigrade-ci tardigrade-ci  4096 Jul 28 19:56 .github
-rw-r--r-- 1 tardigrade-ci tardigrade-ci  1344 Jul 28 19:56 .gitignore
-rw-r--r-- 1 tardigrade-ci tardigrade-ci   460 Jul 25 14:40 .mergify.yml
-rw-r--r-- 1 tardigrade-ci tardigrade-ci  3266 Jul 26 16:51 .tardigrade-ci
-rw-r--r-- 1 tardigrade-ci tardigrade-ci  2489 Jul 28 19:56 .travis.yml
-rw-r--r-- 1 tardigrade-ci tardigrade-ci   131 Jul 28 20:09 Dockerfile
-rw-r--r-- 1 tardigrade-ci tardigrade-ci 11382 Jul 25 14:40 LICENSE
-rw-r--r-- 1 tardigrade-ci tardigrade-ci   638 Jul 28 19:56 Makefile
-rw-r--r-- 1 tardigrade-ci tardigrade-ci  4931 Jul 28 19:56 README.md
-rw-r--r-- 1 tardigrade-ci tardigrade-ci   282 Jul 28 19:56 file_cache.py
-rw-r--r-- 1 tardigrade-ci tardigrade-ci   311 Jul 28 19:56 main.tf
-rw-r--r-- 1 tardigrade-ci tardigrade-ci   166 Jul 25 14:40 outputs.tf
drwxr-xr-x 3 tardigrade-ci tardigrade-ci  4096 Jul 28 19:56 py_getter
-rw-r--r-- 1 tardigrade-ci tardigrade-ci    18 Jul 28 19:56 requirements.txt
drwxr-xr-x 4 tardigrade-ci tardigrade-ci  4096 Jul 28 19:56 tests
drwxr-xr-x 3 tardigrade-ci tardigrade-ci  4096 Jul 28 19:56 tf_external
-rw-r--r-- 1 tardigrade-ci tardigrade-ci   745 Jul 28 19:56 variables.tf

tardigrade-ci@ddee8c78a775:/workdir$ ls -al /tardigrade-ci/tests/terraform_pytest
total 40
drwxr-xr-x 5 tardigrade-ci tardigrade-ci 4096 Jul 28 01:20 .
drwxr-xr-x 5 tardigrade-ci tardigrade-ci 4096 Jul 16 02:46 ..
drwxr-xr-x 3 tardigrade-ci tardigrade-ci 4096 Jul 28 01:20 .pytest_cache
drwxr-xr-x 2 tardigrade-ci tardigrade-ci 4096 Jul 28 01:18 __pycache__
-rw-r--r-- 1 tardigrade-ci tardigrade-ci   42 Jul 16 17:32 aws.tf
-rw-r--r-- 1 tardigrade-ci tardigrade-ci 3935 Jul 16 17:32 conftest.py
-rw-r--r-- 1 tardigrade-ci tardigrade-ci  481 Jul 16 17:32 docker-compose-localstack.yml
drwxr-xr-x 2 tardigrade-ci tardigrade-ci 4096 Jul 16 17:32 initaws.d
-rw-r--r-- 1 tardigrade-ci tardigrade-ci 2553 Jul 26 23:23 mockstack.tf
-rw-r--r-- 1 tardigrade-ci tardigrade-ci 2664 Jul 22 17:40 test_terraform_install.py

tardigrade-ci@ddee8c78a775:/workdir$ ls -al /workdir/tests/filecache/prereq
total 28
drwxr-xr-x 2 tardigrade-ci tardigrade-ci  4096 Jul 29 02:02 .
drwxr-xr-x 4 tardigrade-ci tardigrade-ci  4096 Jul 28 20:01 ..
-rw-r--r-- 1 tardigrade-ci tardigrade-ci   324 Jul 28 19:56 main.tf
-rw-r--r-- 1 tardigrade-ci tardigrade-ci 14861 Jul 28 20:01 terraform.tfstate.backup
```

**Comment by kbalk** [comment]
My output of your commands is shown below.  There is no group or user of 1001 in that docker container.  However, on my VB, the command `id -u` yields a value of 1001.

```
[130]$ docker run --network terraform_pytest_default --rm -e MOCKSTACK_HOST=localstack -e PYTEST_ARGS="" -v "/home/kbalk/plus3it/terraform-external-file-cache/:/workdir/" -v "/home/kbalk/plus3it/tardigrade-ci/:/tardigrade-ci/" -v "/home/kbalk/.aws/:/root/.aws/" -e AWS_DEFAULT_REGION=us-east-1 -w /workdir/ --entrypoint bash -it terraform-external-file-cache-integration-test:latest
tardigrade-ci@079380cc9c1e:/workdir$ whoami
tardigrade-ci
tardigrade-ci@079380cc9c1e:/workdir$ pwd
/workdir
tardigrade-ci@079380cc9c1e:/workdir$ ls -al
total 80
drwxrwxr-x. 7 1001 1001  4096 Jul 28 21:53 .
drwxr-xr-x. 1 root root    33 Jul 29 14:11 ..
-rw-rw-r--. 1 1001 1001   130 Jul 28 19:01 .bumpversion.cfg
-rw-rw-r--. 1 1001 1001   333 Jul 28 19:01 .editorconfig
drwxrwxr-x. 8 1001 1001   220 Jul 28 19:03 .git
-rw-rw-r--. 1 1001 1001    68 Jul 28 18:06 .gitattributes
drwxrwxr-x. 2 1001 1001    28 Jul 28 19:01 .github
-rw-rw-r--. 1 1001 1001  1344 Jul 28 19:01 .gitignore
-rw-rw-r--. 1 1001 1001   460 Jul 28 18:06 .mergify.yml
-rw-rw-r--. 1 1001 1001  3266 Jul 28 21:53 .tardigrade-ci
-rw-rw-r--. 1 1001 1001  2489 Jul 28 19:01 .travis.yml
-rw-rw-r--. 1 1001 1001   123 Jul 28 21:51 Dockerfile
-rw-rw-r--. 1 1001 1001 11382 Jul 28 18:06 LICENSE
-rw-rw-r--. 1 1001 1001   638 Jul 28 19:01 Makefile
-rw-rw-r--. 1 1001 1001  4931 Jul 28 19:01 README.md
-rw-rw-r--. 1 1001 1001   282 Jul 28 19:01 file_cache.py
-rw-rw-r--. 1 1001 1001   311 Jul 28 19:01 main.tf
-rw-rw-r--. 1 1001 1001   166 Jul 28 18:06 outputs.tf
drwxrwxr-x. 2 1001 1001    71 Jul 28 21:55 py_getter
-rw-rw-r--. 1 1001 1001    18 Jul 28 19:01 requirements.txt
drwxrwxr-x. 4 1001 1001    38 Jul 28 19:01 tests
drwxrwxr-x. 2 1001 1001    25 Jul 28 21:55 tf_external
-rw-rw-r--. 1 1001 1001   745 Jul 28 19:01 variables.tf
tardigrade-ci@079380cc9c1e:/workdir$ 
```

**Comment by lorengordon** [comment]
Oh, I see it now. The command `id -u` resolves to 1001 for you, but I had copy/pasta'd the wrong variable name in the docker build command. It worked for me because my local UID/GID is 1000 (same as the default in the Dockerfile). One sec...

**Comment by kbalk** [comment]
Close, but no cigar, see below.  The `.pytest_cache` directory is owned by root; it exists in the docker container and not in my VB directory.

```
pytest /tardigrade-ci/tests/terraform_pytest 
============================= test session starts ==============================
platform linux -- Python 3.9.6, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
rootdir: /tardigrade-ci/tests/terraform_pytest
collected 2 items

../tardigrade-ci/tests/terraform_pytest/test_terraform_install.py ..     [100%]

=============================== warnings summary ===============================
../home/tardigrade-ci/.local/lib/python3.9/site-packages/_pytest/cacheprovider.py:428
  /home/tardigrade-ci/.local/lib/python3.9/site-packages/_pytest/cacheprovider.py:428: PytestCacheWarning: cache could not write path /tardigrade-ci/tests/terraform_pytest/.pytest_cache/v/cache/nodeids
    config.cache.set("cache/nodeids", sorted(self.cached_nodeids))

../home/tardigrade-ci/.local/lib/python3.9/site-packages/_pytest/stepwise.py:49
  /home/tardigrade-ci/.local/lib/python3.9/site-packages/_pytest/stepwise.py:49: PytestCacheWarning: cache could not write path /tardigrade-ci/tests/terraform_pytest/.pytest_cache/v/cache/stepwise
    session.config.cache.set(STEPWISE_CACHE_DIR, [])

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 2 passed, 2 warnings in 59.59s ========================
[pytest//tardigrade-ci/tests/terraform_pytest]: Tests executed!
[mockstack/pytest]: Completed successfully!
```

**Comment by lorengordon** [comment]
Fairly sure that directory is in your VB directory, `/home/kbalk/plus3it/tardigrade-ci/tests/terraform_pytest`. That `tardigrade-ci` directory gets mounted to the container as `/tardigrade-ci/`, so docker previously created the directory `.pytest_cache` as root.

**Comment by kbalk** [comment]
I did a `ls -l` vs. `ls -la`, so I missed that directory.  The latest changes work as long as the user doesn't already have a copy of tardigrade-ci and files within it owned by root.

**Comment by kbalk** [comment]
Still need a changelog update?  Should I go ahead and approve this request?

**Comment by lorengordon** [comment]
Thanks! And yep, unfortunately this can't "fix" a local setup that ran previously and created local files owned by root.

Updated the changelog and bumped the version, removed the WIP title. Should be ready for a final review/approval.

**Review by kbalk — DISMISSED** [review]

**Comment by lorengordon** [comment]
Oops, noticed the PATH was incorrect for the non-root user. Fixed, and requested re-review.

**Review by kbalk — APPROVED** [review]

**Pull request merged**
